### ISSUE TITLE
Test JAX as better PyTorch autograd

### ISSUE THREAD

**Issue by karlb** [HolgerBartel/Causing#13]
This might be useful in the long run.

Details at https://moocaholic.medium.com/jax-a13e83f49897

Migrated from https://realrate.atlassian.net/browse/CAUSING-84

**Comment by Holger-Bartel** [comment]
See also https://medium.com/syncedreview/google-proposes-efficient-and-modular-implicit-differentiation-for-optimization-problems-8fd60a496b6e, where JAX is used.

**Comment by karlb** [comment]
We don't us Pytorch, anymore.
