### ISSUE TITLE
Check and update documentation

### ISSUE THREAD

**Issue by karlb** [HolgerBartel/Causing#48]
To make Causing usable by people outside of RealRate, we provide documentation at
* https://github.com/realrate/Causing/blob/develop/README.md
* https://github.com/realrate/Causing/blob/develop/docs/education.md

This documentation has been written a while ago and has only been updated sporadically. Read the documentation and look for the following problems (on the develop branch):

- [x] Is it understandable to new users (being able to use it is sufficient, no deep math understanding required)?
- [x] Is it up to date with the code base (general content should be ok, but check code samples and code references)?
- [x] Does the code yield the same results as shown in the documentation?

**Comment by salistha-shakya** [comment]
Yes, the code is understandable to new users but it was supposed to give output in PNG and PDF file format whereas we are receiving SVG graph.

**Comment by karlb** [comment]
> Yes, the code is understandable to new users but it was supposed to give output in PNG and PDF file format whereas we are receiving SVG graph.

That is an acceptable change. Please update the documentation to describe the current behavior.
