### ISSUE TITLE
Graphs with Broad Edges 

### ISSUE THREAD

**Issue by salistha-shakya** [HolgerBartel/Causing#80]
We should try modifying our causal Graphviz graphs to have extremely broad Edges. There is the "penwidth" argument for edges in Graphviz:
https://stackoverflow.com/questions/2333025/graphviz-changing-the-size-of-edge
https://graphviz.org/docs/edges/

Related to https://github.com/realrate/RealRate-Private/issues/1416

**Comment by HolgerBartel** [comment]
@salistha-shakya I guess this is done?

**Comment by salistha-shakya** [comment]
Yes. Handled at https://github.com/realrate/Causing/pull/81
