### ISSUE TITLE
LLPO encountered division by zero 

### ISSUE THREAD

**Issue by KrishaKumaleManandhar** [HolgerBartel/Causing#82]
An exception of Floating Error where ECR_after_LLPO was set to 0 instead of LLPO in causing/model.py is leading to all ECRs to zero

![Screenshot from 2024-12-16 13-05-26](https://github.com/user-attachments/assets/514b5f54-cd86-446c-86e7-c8c87a0aeee7)

**Comment by Holger-Bartel** [comment]
@KrishaKumaleManandhar @bbkrr and that is a great find indeed (not new, we saw that earlier). In case of a numeric error we want to set LLPO to zero NOT ECR. 
Anyway, now that you have the new LLPO proxy we should DELETE that code. May this was the error we have been looking for all the time?
